<a href="https://colab.research.google.com/github/tanviraut980/Session-20-Assignment/blob/main/Session_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving ford_car_dataset.csv to ford_car_dataset (1).csv

In [ ]:
df=pd.read_csv("/content/ford_car_dataset.csv")

In [ ]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [ ]:
print("Independent Features:")
X=df.drop("price",axis=1)
X.head()

Independent Features:

     model  year transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019    Automatic     1482   Petrol  145  48.7         1.0

In [ ]:
print("Dependent Features:")
Y=df["price"]
Y.head()

Dependent Features:

0    12000
1    14000
2    13000
3    17500
4    16500
Name: price, dtype: int64

In [ ]:
print("Shape of X:",X.shape)

Shape of X: (17966, 8)

In [ ]:
print("Shape of Y:",Y.shape)

Shape of Y: (17966,)

In [ ]:
df_encoded=pd.get_dummies(X,columns=["model","transmission","fuelType"])
df_encoded=df_encoded.astype(int)
print("After Encoding:")
print(df_encoded.head())

After Encoding:
   year  mileage  tax  mpg  engineSize  model_ B-MAX  model_ C-MAX  \
0  2017    15944  150   57           1             0             0
1  2018     9083  150   57           1             0             0
2  2017    12456  150   57           1             0             0
3  2019    10460  145   40           1             0             0
4  2019     1482  145   48           1             0             0

   model_ EcoSport  model_ Edge  model_ Escort  ...  model_ Transit Tourneo  \
0                0            0              0  ...                       0
1                0            0              0  ...                       0
2                0            0              0  ...                       0
3                0            0              0  ...                       0
4                0            0              0  ...                       0

   model_Focus  transmission_Automatic  transmission_Manual  \
0            0                       1                    0
1            0                       0                    1
2            0                       0                    1
3            0                       0                    1
4            0                       1                    0

   transmission_Semi-Auto  fuelType_Diesel  fuelType_Electric  \
0                       0                0                  0
1                       0                0                  0
2                       0                0                  0
3                       0                0                  0
4                       0                0                  0

   fuelType_Hybrid  fuelType_Other  fuelType_Petrol
0                0               0                1
1                0               0                1
2                0               0                1
3                0               0                1
4                0               0                1

[5 rows x 37 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

col=["year","mileage","tax","mpg","engineSize"]

scaler=StandardScaler()

df_encoded[col]=scaler.fit_transform(df_encoded[col])
df_encoded[col].head()

       year   mileage       tax       mpg  engineSize
0  0.065128 -0.380998  0.591358 -0.042122   -0.447984
1  0.552866 -0.733359  0.591358 -0.042122   -0.447984
2  0.065128 -0.560132  0.591358 -0.042122   -0.447984
3  1.040605 -0.662640  0.510727 -1.721198   -0.447984
4  1.040605 -1.123724  0.510727 -0.931045   -0.447984

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train,X_test,Y_train,Y_test=train_test_split(df_encoded,Y,test_size=0.33,random_state=42)

In [ ]:
X_train.shape

(12037, 37)

In [ ]:
X_test.shape

(5929, 37)

In [ ]:
Y_train.shape

(12037,)

In [ ]:
Y_test.shape

(5929,)

In [ ]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
print("Intercept:",model.intercept_)
print("\nCoefficients:",model.coef_)

Intercept: 17008.928804463576

Coefficients: [ 2.03726418e+03 -1.31955378e+03 -2.12184657e+01 -9.89026938e+02
  8.79613637e+02 -3.65234589e+03 -2.68053102e+03 -2.36339814e+03
  4.80150971e+03  1.02450948e+04 -2.72586392e+03 -6.34300645e+02
 -1.61638167e+02  2.03975409e+03 -2.41408106e+03  3.63649958e+02
 -4.09377412e+03 -6.56211930e+03 -4.23908486e+02 -1.23180996e+03
  9.37077816e+03  3.56715981e+03  7.27595761e-12  1.88351384e+03
  9.09494702e-13 -2.25529492e+02  1.90037677e+03 -2.78174995e+03
 -4.22078695e+03  2.52157947e+02 -2.56550681e+02  4.39273388e+00
 -2.00100839e+03  0.00000000e+00  6.64511383e+03 -1.34334791e+03
 -3.30075753e+03]

In [ ]:
y_pred=model.predict(X_test)
print("Predicted value:",y_pred[:10])
print("\nActual value:",Y_test.tolist()[:10])

Predicted value: [ 6888.75487917  9328.62297666  9420.53085767  4495.6044587
  2429.68493278 16982.00675592 28491.10791141 12482.71267443
 11373.08042083 17275.68925414]

Actual value: [6995, 8999, 7998, 5491, 3790, 18200, 22998, 11000, 7600, 14985]

In [ ]:
from sklearn.metrics import r2_score

r2=r2_score(Y_test,y_pred)
print("R2 Score:",r2)

r2: 0.8401880779365886

In [ ]:
#R2 is 84 means the model explains 84% of the variation in car prices.
#It is performing very well

In [ ]:
import joblib
joblib.dump(model,'model.pkl')
joblib.dump(StandardScaler,'scaler.pkl')
joblib.dump(X_train.columns.tolist(),"columns.pkl")

['columns.pkl']